{
    "config": {
        "error": {
            "cannot_connect": "Nie mo\u017cna nawi\u0105za\u0107 po\u0142\u0105czenia",
            "invalid_auth": "Niepoprawne uwierzytelnienie",
            "unknown": "Nieoczekiwany b\u0142\u0105d"
        },
        "step": {
            "auth": {
                "data": {
                    "password": "Has\u0142o",
                    "username": "Nazwa u\u017cytkownika"
                },
                "description": "Urz\u0105dzenie IoTawatt wymaga uwierzytelnienia. Wprowad\u017a nazw\u0119 u\u017cytkownika i has\u0142o, a nast\u0119pnie kliknij przycisk \"Zatwierd\u017a\"."
            },
            "user": {
                "data": {
                    "host": "Host"
                }
            }
        }
    }
}